server:
  port: ${SERVER_PORT:8080}
  max-http-request-header-size: 128KB
  tomcat:
    threads:
      min-spare: 0
    mbeanregistry:
      enabled: true

debug: ${DEBUG:false}

spring:
  application:
    name: ${APP_NAME:tm-backend}
  devtools:
    livereload:
      enabled: false
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost:5432}/${DB_DATABASE:speedrun}?ApplicationName=${speedrun.jdbc-name}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:}

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: {DEBUG_FORMAT_SQL:false}
        generate_statistics: true
        session:
          events:
            log: false
  profiles:
    active: speedrun

management:
  server:
    port: ${METRICS_PORT:8090}
  endpoints:
    web:
      base-path: /stat
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
      group:
        liveness:
          include:
            - livenessState
            - db
  health:
    defaults:
      enabled: false
    db:
      enabled: true
    ping:
      enabled: true
  info:
    defaults:
      enabled: false
    build:
      enabled: true
    os:
      enabled: true
    java:
      enabled: true
  defaults:
    metrics:
      export:
        enabled: false
  prometheus:
    metrics:
      export:
        enabled: true

logging:
  level:
    org:
      springframework:
        boot: INFO
        boot.actuate.endpoint.web.servlet: INFO
        boot.autoconfigure: WARN
        web: INFO
    sql: INFO
    org.hibernate.orm.jdbc.bind: INFO
    ru:
      speedrun:
        speedrun: ${LOG_LEVEL:DEBUG}
